version: "3"

services:
  app:
    image: shyfrost/focus-ssr
    command: gunicorn --bind 0.0.0.0:7000 manage:app
    expose:
      - 7000
    links:
      - redis:redis
    depends_on:
      - redis

  proxy:
    image: shyfrost/focus-ssr-nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - app

  postgres:
    image: postgres:13.8-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db

  redis:
    image: redis:alpine
    expose:
      - "6379"           