version: "3"

services:
  app:
    image: shyfrost/focus-ssr:latest
    expose:
      - 7000

  nginx:
    image: nginx:1.13-alpine
    restart: always
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app

  postgres:
    image: postgres:13.8-alpine
    ports:
      - "5432:5432"
    volumes:
     - ./postgres-data/:/var/lib/postgresql/data
    env_file:
      - ./.env.db

  redis:
    image: redis:alpine
    expose:
      - 6379