apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: focus-ssr
spec:
  replicas: 3
  selector:
    matchLabels:
      name: focus-ssr
  template:
    metadata:
      labels:
        name: focus-ssr
    spec:
      containers:
      - name: focus-ssr
        image: shyfrost/focus-ssr
        ports:
        - containerPort: 80
          name: http