on: push
name: deploy
jobs:

  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v1
    - 
      name: build and push to docker focus-ssr
      uses: docker/build-push-action@v2
      with:
        context: app
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tags: shyfrost/focus-ssr:latest

    - 
      name: build and push to docker focus-ssr-nginx
      uses: docker/build-push-action@v2
      with:
        context: nginx
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tags: shyfrost/focus-ssr-nginx:latest
        
    -
      name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: kubectl apply -f .
    - 
      name: install load balancer
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: kubectl expose deployment proxy --type=LoadBalancer --name=lb-service