on: push
name: deploy
jobs:

  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: build and push to docker focus-ssr
      uses: docker/build-push-action@v2
      with:
        context: ./app
        push: true
        repository: ${{ github.repository }}
    - 
      uses: actions/checkout@v3
    -
      name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f .
    - 
      name: install load balancer
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: kubectl expose deployment proxy --type=LoadBalancer --name=lb-service